import { Inter } from "next/font/google";
import "./globals.css";
import { store } from "./redux/store/store";
import { Provider } from "react-redux";
import GeneralProvider from "./redux/Provider/GeneralProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quickbaya | Live ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GeneralProvider>{children}</GeneralProvider>
      </body>
    </html>
  );
}
